version: "3"
services:
  ngnix:
    image: ngnix:stable-alpine
  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    # depends_on:
    #   - mongo

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
